"""Preview and place bounded MIDI clip plans on Live's execution thread.

Plans retain Live object references. They are process-local, expire quickly and
never use track/clip positions as identity after preview. No Live imports are
needed here; the control surface supplies access to its current Song and notes.
"""

import copy
import hashlib
import json
import math
import time
import uuid
from collections import OrderedDict


MAX_PLACEMENTS = 64
MAX_PLAN_NOTES = 10000
MAX_EXISTING_CLIPS = 4096
MAX_PLANS = 32
PLAN_TTL_SECONDS = 300
_CLIP_FIELDS = ("name", "length", "looping", "loop_start", "loop_end",
                "start_marker", "end_marker", "muted", "color")


def _same(left, right):
    return left is right or left == right


def _contains(objects, target):
    return any(_same(obj, target) for obj in objects)


def _number(value, name, positive=False):
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(name + " must be a finite number")
    if not math.isfinite(value) or value < 0 or (positive and value == 0):
        raise ValueError(name + " must be finite and " + ("positive" if positive else "nonnegative"))
    return float(value)


def _notes(remote, clip):
    reader = getattr(clip, "get_all_notes_extended", None)
    if not callable(reader):
        raise ValueError("Source cannot be verified: get_all_notes_extended is unavailable")
    notes = reader()
    if len(notes) > MAX_PLAN_NOTES:
        raise ValueError("Source exceeds the 10000-note verification limit")
    rows = remote._serialise_notes(notes, rounded=False)
    for row in rows:
        row.pop("note_id", None)
    # Preserve exact numeric values; IDs are regenerated by clip duplication.
    encoded = [json.dumps(row, sort_keys=True, allow_nan=False) for row in rows]
    return sorted(encoded)


def _source(remote, clip):
    if not getattr(clip, "is_midi_clip", False):
        raise ValueError("Only session MIDI clips are supported")
    try:
        envelopes = clip.has_envelopes
    except Exception as exc:
        raise ValueError("Source clip envelopes cannot be verified: " + str(exc))
    if envelopes not in (False, 0):
        raise ValueError("Source clip has envelopes; Live strips these when copying to arrangement")
    metadata = {key: getattr(clip, key) for key in _CLIP_FIELDS}
    _number(metadata["length"], "source length", positive=True)
    notes = _notes(remote, clip)
    fingerprint = hashlib.sha256(json.dumps(
        {"clip": metadata, "notes": notes}, sort_keys=True,
        allow_nan=False).encode("utf-8")).hexdigest()
    return {"metadata": metadata, "notes": notes, "fingerprint": fingerprint}


def _arrangement(track):
    clips = tuple(track.arrangement_clips)
    if len(clips) > MAX_EXISTING_CLIPS:
        raise ValueError("Track exceeds the 4096-clip overlap verification limit")
    return clips


def _check_ranges(entries):
    for index, entry in enumerate(entries):
        start, end = entry["start"], entry["end"]
        existing = _arrangement(entry["track"])
        additions = sum(1 for other in entries if _same(other["track"], entry["track"]))
        if len(existing) + additions > MAX_EXISTING_CLIPS:
            raise ValueError("Plan would exceed the 4096-clip overlap verification limit")
        for clip in existing:
            clip_start = _number(clip.start_time, "existing clip start")
            clip_end = _number(clip.end_time, "existing clip end")
            if clip_end <= clip_start:
                raise ValueError("Existing arrangement clip has unverifiable bounds")
            if clip_start < end and clip_end > start:
                raise ValueError("Placement {0} overlaps existing arrangement clip '{1}'".format(
                    index + 1, clip.name))
        for other in entries[:index]:
            if _same(entry["track"], other["track"]) and other["start"] < end and other["end"] > start:
                raise ValueError("Placement {0} overlaps another proposed placement".format(index + 1))


def _eligible(track):
    if getattr(track, "is_foldable", False):
        raise ValueError("Group tracks cannot receive clip placements")
    if getattr(track, "is_frozen", False):
        raise ValueError("Frozen tracks cannot receive clip placements")


def _targets(remote, session_id):
    targets = remote._get_edit_targets()
    if not session_id or targets["session_id"] != session_id:
        raise ValueError("Stale Set identity; refresh get_edit_targets")
    return targets


def _public(entry, index):
    return {"index": index + 1, "track_handle": entry["handle"],
            "track_name": entry["track"].name, "source_slot": entry["slot"] + 1,
            "source_name": entry["source"]["metadata"]["name"],
            "destination_beat": entry["start"], "end_beat": entry["end"],
            "length_beats": entry["end"] - entry["start"],
            "note_count": len(entry["source"]["notes"]),
            "source_fingerprint": entry["source"]["fingerprint"]}


def _preview(remote, session_id, placements, plans):
    if not isinstance(placements, list) or not 1 <= len(placements) <= MAX_PLACEMENTS:
        raise ValueError("placements must contain 1 to 64 entries")
    targets = _targets(remote, session_id)
    song = remote._song
    rows = {row["track_handle"]: row for row in targets["tracks"]}
    entries, note_count = [], 0
    for placement in placements:
        if not isinstance(placement, dict) or set(placement) != {
                "track_handle", "source_slot", "destination_beat"}:
            raise ValueError("Each placement requires only track_handle, source_slot and destination_beat")
        handle = placement["track_handle"]
        if not isinstance(handle, str) or handle not in rows or rows[handle]["kind"] != "track":
            raise ValueError("Placement requires a current regular track handle")
        track = remote._target_refs[handle]
        _eligible(track)
        slot_index = placement["source_slot"]
        if isinstance(slot_index, bool) or not isinstance(slot_index, int) or slot_index < 1:
            raise ValueError("source_slot must be a 1-based integer")
        slots = tuple(track.clip_slots)
        if slot_index > len(slots) or not slots[slot_index - 1].has_clip:
            raise ValueError("Source slot is empty or out of range")
        clip = slots[slot_index - 1].clip
        source = _source(remote, clip)
        note_count += len(source["notes"])
        if note_count > MAX_PLAN_NOTES:
            raise ValueError("Plan exceeds the 10000-note verification limit")
        start = _number(placement["destination_beat"], "destination_beat")
        end = _number(start + source["metadata"]["length"], "placement end", positive=True)
        entries.append({"handle": handle, "track": track, "clip": clip,
                        "slot": slot_index - 1, "source": source,
                        "start": start, "end": end})
    _check_ranges(entries)
    if not _same(remote._song, song):
        raise ValueError("Set changed during preview; refresh the plan")
    now = time.monotonic()
    plan_id = str(uuid.uuid4())
    result = {"status": "preview", "plan_id": plan_id, "session_id": session_id,
              "expires_in_seconds": PLAN_TTL_SECONDS,
              "placements": [_public(entry, i) for i, entry in enumerate(entries)],
              "placement_count": len(entries), "note_count": note_count,
              "warnings": ["Copies session MIDI clips on their own tracks. No source changes, playback or file save.",
                           "Source guards cover clip metadata and exposed MIDI note values; per-note expression is not inspected."]}
    while len(plans) >= MAX_PLANS:
        plans.popitem(last=False)
    plans[plan_id] = {"song": song, "session_id": session_id, "created": now,
                      "entries": entries, "status": "preview", "result": result}
    return copy.deepcopy(result)


def _validate_plan(remote, plan, session_id):
    targets = _targets(remote, session_id)
    if plan["session_id"] != session_id or not _same(remote._song, plan["song"]):
        raise ValueError("Plan belongs to a different Set instance")
    if (getattr(remote, "_auto_rec", None) or {}).get("active"):
        raise ValueError("Finish or cancel the active recording job before placing arrangement clips")
    for entry in plan["entries"]:
        handle, track = entry["handle"], entry["track"]
        if handle not in remote._target_refs or not _same(remote._target_refs[handle], track):
            raise ValueError("Plan track was deleted or replaced")
        if not _contains(tuple(plan["song"].tracks), track):
            raise ValueError("Plan requires a current regular track")
        _eligible(track)
        slots = tuple(track.clip_slots)
        index = entry["slot"]
        if index >= len(slots) or not slots[index].has_clip or not _same(slots[index].clip, entry["clip"]):
            raise ValueError("Source clip was moved, deleted or replaced since preview")
        if _source(remote, entry["clip"])["fingerprint"] != entry["source"]["fingerprint"]:
            raise ValueError("Source clip changed since preview; create a new plan")
    _check_ranges(plan["entries"])
    return targets


def _apply(remote, session_id, plan_id, plans):
    plan = plans.get(plan_id)
    if plan is None:
        raise ValueError("Unknown or expired plan; create a new preview. Unknown does not prove unapplied.")
    _targets(remote, session_id)
    if plan["session_id"] != session_id or not _same(remote._song, plan["song"]):
        raise ValueError("Plan belongs to a different Set instance")
    if plan["status"] in ("applied", "error", "partial"):
        result = copy.deepcopy(plan["result"])
        result["replayed"] = True
        return result
    if time.monotonic() - plan["created"] > PLAN_TTL_SECONDS:
        raise ValueError("Plan expired; create a new preview")
    if plan["status"] != "preview":
        raise ValueError("Plan is already applying; reconcile the original request before continuing")
    _validate_plan(remote, plan, session_id)
    owned, placed, rollback_errors = [], [], []
    initial = []
    for entry in plan["entries"]:
        if not any(_same(track, entry["track"]) for track, _clips in initial):
            initial.append((entry["track"], _arrangement(entry["track"])))
    plan["status"] = "applying"
    undo_song = None
    try:
        undo_song = remote._begin_note_undo()
        for index, entry in enumerate(plan["entries"]):
            track = entry["track"]
            before = _arrangement(track)
            try:
                track.duplicate_clip_to_arrangement(entry["clip"], entry["start"])
            finally:
                after = _arrangement(track)
                created = [clip for clip in after if not _contains(before, clip)]
                owned.extend((track, clip) for clip in created)
            if len(created) != 1:
                raise RuntimeError("Copy did not produce exactly one identifiable arrangement clip")
            clip = created[0]
            if not all(_contains(after, old) for old in before):
                raise RuntimeError("Copy unexpectedly replaced existing arrangement material")
            actual_start = _number(clip.start_time, "placed clip start")
            actual_end = _number(clip.end_time, "placed clip end", positive=True)
            if abs(actual_start - entry["start"]) > 0.00001 or abs(actual_end - entry["end"]) > 0.00001:
                raise RuntimeError("Placed clip bounds differ from the preview")
            if _notes(remote, clip) != entry["source"]["notes"]:
                raise RuntimeError("Placed MIDI note values differ from the preview")
            record = _public(entry, index)
            record.update(status="verified", actual_start_beat=clip.start_time,
                          actual_end_beat=clip.end_time, actual_name=clip.name)
            placed.append(record)
        if undo_song is not None:
            undo_song.end_undo_step()
            undo_song = None
        result = {"status": "applied", "plan_id": plan_id, "session_id": session_id,
                  "placements": placed, "placement_count": len(placed),
                  "replayed": False, "saved": False}
    except Exception as exc:
        for track, clip in reversed(owned):
            try:
                if not _same(remote._song, plan["song"]) or not _contains(tuple(plan["song"].tracks), track):
                    raise RuntimeError("Owning Set or track is no longer available")
                if _contains(_arrangement(track), clip):
                    track.delete_clip(clip)
                if _contains(_arrangement(track), clip):
                    raise RuntimeError("Created clip remains after rollback")
            except Exception as rollback_exc:
                rollback_errors.append(str(rollback_exc))
        for track, originals in initial:
            try:
                current = _arrangement(track)
                if not all(_contains(current, clip) for clip in originals):
                    rollback_errors.append("Original arrangement material is missing after failed copy")
                if any(not _contains(originals, clip) for clip in current):
                    rollback_errors.append("New arrangement material remains after failed copy")
            except Exception as rollback_exc:
                rollback_errors.append("Cannot verify original arrangement: " + str(rollback_exc))
        if undo_song is not None:
            try:
                undo_song.end_undo_step()
            except Exception as undo_exc:
                rollback_errors.append("Could not close undo group: " + str(undo_exc))
        result = {"status": "partial" if rollback_errors else "error", "plan_id": plan_id,
                  "session_id": session_id, "message": str(exc),
                  "placements": [dict(row, status="rollback_unverified" if rollback_errors else "rolled_back")
                                 for row in placed],
                  "placement_count": len(plan["entries"]),
                  "completed_before_failure": len(placed), "rollback_verified": not rollback_errors,
                  "rollback_errors": rollback_errors, "replayed": False, "saved": False}
    plan["status"], plan["result"] = result["status"], result
    return copy.deepcopy(result)


def build_arrangement(remote, action, session_id, placements=None, plan_id=""):
    """Called only on the Remote Script's scheduled execution thread."""
    if action not in ("preview", "apply"):
        raise ValueError("action must be preview or apply")
    if not isinstance(session_id, str) or not session_id:
        raise ValueError("session_id is required")
    if not hasattr(remote, "_arrangement_plans"):
        remote._arrangement_plans = OrderedDict()
    plans = remote._arrangement_plans
    if action == "preview":
        if plan_id:
            raise ValueError("Preview does not accept plan_id")
        return _preview(remote, session_id, placements, plans)
    if placements:
        raise ValueError("Apply accepts the retained plan_id, not replacement placements")
    if not isinstance(plan_id, str) or not plan_id:
        raise ValueError("Apply requires plan_id from a successful preview")
    return _apply(remote, session_id, plan_id, plans)
